site_name: Documentation Papillon
site_url: https://docs.getpapillon.xyz
repo_url: https://github.com/PapillonApp/docs
repo_name: PapillonApp/docs
nav:
  - Accueil: 'index.md'
  - Aide de Papillon: 'help/index.md'
  - Documents :
    - Conditions de service : 'documents/terms-of-service.md'
    - Kit de communication : 'documents/communication-kit.md'
  - API :
    - Déploiement de l'API : 'api/deployment.md'
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  language: fr
  logo: assets/logo.svg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate 
plugins:
  - search
  - git-revision-date-localized:
      locale: fr
      type: timeago
      fallback_to_build_date: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PapillonApp/Papillon
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/thepapillonapp/
    - icon: fontawesome/brands/discord
      link: https://discord.getpapillon.xyz/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
